# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# SPDX-License-Identifier: Apache-2.0

FROM debian

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y build-essential curl

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    echo . "$HOME/.cargo/env" >> ~/.bashrc

RUN apt-get install -y gcc-aarch64-linux-gnu pkg-config clang libclang-dev

ENV PATH="/root/.cargo/bin:${PATH}"

RUN rustup target add aarch64-unknown-linux-gnu

WORKDIR /app

RUN dpkg --add-architecture arm64 && apt-get update

RUN apt-get install -y libtss2-dev:arm64

ENV PKG_CONFIG_SYSROOT_DIR="/"
ENV PKG_CONFIG_PATH="/usr/lib/aarch64-linux-gnu/pkgconfig"
ENV CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER="aarch64-linux-gnu-gcc"

ENTRYPOINT ["/usr/bin/bash"]
