# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# SPDX-License-Identifier: CC0-1.0

[target.armv7-unknown-linux-musleabihf]
pre-build = [
  # additional commands to run prior to building the package
  "dpkg --add-architecture armhf",
  "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get --assume-yes install cmake clang",
]
