realm = "example_realm"
device_id = "YOUR_UNIQUE_DEVICE_ID"
pairing_url = "https://api.astarte.EXAMPLE.COM/pairing"
grpc_socket_port = 50051
interfaces_directory = "/usr/share/message-hub/astarte-interfaces/"
pairing_token = "YOUR_PAIRING_TOKEN"
# credentials_secret = "YOUR_CREDENTIAL_SECRET"
store_directory = "/var/lib/message-hub"

[astarte]
ignore_ssl = false
# keep_alive_secs = 30
# timeout_secs = 5
