# This file is part of Astarte.
#
# Copyright 2025 SECO Mind Srl
#
# SPDX-License-Identifier: Apache-2.0

name: Release ci
on:
  release:
    types: [published]
permissions:
  contents: read
# Spend CI time only on latest ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  reuse:
    uses: ./.github/workflows/reuse-lint.yaml
  check:
    uses: ./.github/workflows/check.yaml
    needs: [reuse]
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
    needs: [reuse]
  e2e-test:
    uses: ./.github/workflows/e2e-test.yaml
    needs: [reuse]
  multi-platform:
    uses: ./.github/workflows/multi-platform.yaml
    needs: [reuse]
  publish-release:
    secrets: inherit
    uses: ./.github/workflows/ghcr-publish-release.yaml
    needs:
      - check
      - test
      - e2e-test
      - multi-platform
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
